# -*- coding: utf-8 -*-
"""
@file test_dynamical_equations.py
@brief Unit tests for PSO velocity update kernels.

This module contains unit tests for the velocity update kernels generated by
`make_update_velocity` in `dynamical_equations.py`.

The tests verify:

- Correct inertia-formulation velocity updates
- Correct constriction-formulation velocity updates
- Proper elementwise vector arithmetic
- Reduction to pure inertia when acceleration terms vanish
- Reduction to pure inertia when pbest and lbest equal the current position
- Independence of the constriction formulation from the inertia parameter
- Preservation of input arrays
- Output array shape and dtype consistency
- Proper handling of unsupported dynamical equation types

The tests are deterministic and designed for use with pytest.

@author
Ben Carlson

@date
2026-06-29
"""

import numpy as np
import pytest
from numpy.testing import assert_allclose
from pathlib import Path

from core.dynamical_equations import make_update_velocity


def build_config(eq_type="inertia", C1=2.0, C2=2.0):
    """
    @brief Construct a minimal PSO configuration object for testing.

    @param eq_type
        Dynamical equation type.

    @param C1
        Cognitive acceleration coefficient.

    @param C2
        Social acceleration coefficient.

    @return
        Lightweight configuration object.
    """

    class DummyConfig:
        pass

    cfg = DummyConfig()
    cfg.C1 = C1
    cfg.C2 = C2
    cfg.eq_type = eq_type

    return cfg


def test_inertia_velocity_update():
    """
    @brief Verify inertia-formulation velocity update.

    Confirms that the returned kernel produces the analytical
    inertia-update equation.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    w = 0.5

    prev_x = np.array([1.0, 2.0, 3.0])
    prev_v = np.array([0.1, 0.2, 0.3])

    R1 = np.ones(3)
    R2 = np.ones(3)

    pbest = np.array([2.0, 3.0, 4.0])
    lbest = np.array([3.0, 4.0, 5.0])

    result = vel_fn(
        w,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    expected = (
        w * prev_v
        + 2.0 * (pbest - prev_x)
        + 2.0 * (lbest - prev_x)
    )

    assert_allclose(result, expected)


def test_constriction_velocity_update():
    """
    @brief Verify constriction-formulation velocity update.

    Confirms that the returned kernel produces the analytical
    constriction-update equation.
    """

    config = build_config("constriction")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0, 2.0])
    prev_v = np.array([0.1, 0.2])

    R1 = np.ones(2)
    R2 = np.ones(2)

    pbest = np.array([2.0, 3.0])
    lbest = np.array([3.0, 4.0])

    result = vel_fn(
        999.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    phi = 4.0

    K = 2.0 / abs(
        2.0 - phi - np.sqrt(phi * phi - 4.0 * phi)
    )

    expected = K * (
        prev_v
        + 2.0 * (pbest - prev_x)
        + 2.0 * (lbest - prev_x)
    )

    assert_allclose(result, expected)


def test_inertia_elementwise_behavior():
    """
    @brief Verify velocity updates are performed independently for each
    coordinate.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([10.0, -10.0])
    prev_v = np.array([1.0, 2.0])

    R1 = np.array([0.5, 2.0])
    R2 = np.array([1.0, 1.0])

    pbest = prev_x.copy()
    lbest = prev_x.copy()

    result = vel_fn(
        1.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    assert_allclose(result, prev_v)
    
def test_constriction_elementwise_behavior():
    """
    @brief Verify constriction-formulation updates are performed
    independently for each coordinate.

    Confirms that each velocity component depends only on the
    corresponding coordinate and is not coupled to the remaining
    dimensions.
    """

    config = build_config("constriction")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([10.0, -10.0])
    prev_v = np.array([1.0, 2.0])

    R1 = np.array([0.5, 2.0])
    R2 = np.array([1.0, 1.0])

    pbest = prev_x.copy()
    lbest = prev_x.copy()

    result = vel_fn(
        123.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    phi = 4.0
    K = 2.0 / abs(
        2.0 - phi - np.sqrt(phi * phi - 4.0 * phi)
    )

    expected = K * prev_v

    assert_allclose(result, expected)


def test_inertia_zero_randomness_reduces_to_inertia():
    """
    @brief Verify zero random vectors eliminate acceleration terms.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    w = 0.7

    prev_x = np.array([1.0, 2.0, 3.0])
    prev_v = np.array([0.5, 0.5, 0.5])

    zeros = np.zeros(3)

    result = vel_fn(
        w,
        prev_x,
        prev_v,
        zeros,
        zeros,
        np.zeros(3),
        np.zeros(3)
    )

    expected = w * prev_v

    assert_allclose(result, expected)
    
    
def test_constriction_zero_randomness_reduces_to_constriction_only():
    """
    @brief Verify zero random vectors eliminate acceleration terms in the
    constriction formulation.

    Confirms that the constriction update reduces to:

    @code
    K * prev_v
    @endcode

    when both random vectors are identically zero.
    """

    config = build_config("constriction")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0, 2.0, 3.0])
    prev_v = np.array([0.5, 0.5, 0.5])

    zeros = np.zeros(3)

    result = vel_fn(
        0.0,
        prev_x,
        prev_v,
        zeros,
        zeros,
        np.zeros(3),
        np.zeros(3)
    )

    phi = 4.0
    K = 2.0 / abs(
        2.0 - phi - np.sqrt(phi * phi - 4.0 * phi)
    )

    expected = K * prev_v

    assert_allclose(result, expected)


def test_inertia_matching_best_locations_reduce_to_inertia():
    """
    @brief Verify acceleration terms vanish when current position equals
    both pbest and lbest.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    w = 0.4

    prev_x = np.array([2.0, 4.0])
    prev_v = np.array([1.0, -2.0])

    R1 = np.array([0.3, 0.8])
    R2 = np.array([0.7, 0.4])

    result = vel_fn(
        w,
        prev_x,
        prev_v,
        R1,
        R2,
        prev_x,
        prev_x
    )

    assert_allclose(result, w * prev_v)
    
    
def test_constriction_matching_best_locations_reduce_to_constriction_only():
    """
    @brief Verify acceleration terms vanish when the current position,
    particle best, and neighborhood best locations are identical.

    In this case the constriction update should reduce to:

    @code
    K * prev_v
    @endcode
    """

    config = build_config("constriction")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([2.0, 4.0])
    prev_v = np.array([1.0, -2.0])

    R1 = np.array([0.3, 0.8])
    R2 = np.array([0.7, 0.4])

    result = vel_fn(
        999.0,
        prev_x,
        prev_v,
        R1,
        R2,
        prev_x,
        prev_x
    )

    phi = 4.0
    K = 2.0 / abs(
        2.0 - phi - np.sqrt(phi * phi - 4.0 * phi)
    )

    expected = K * prev_v

    assert_allclose(result, expected)


def test_constriction_ignores_inertia_parameter():
    """
    @brief Verify constriction formulation ignores the supplied inertia
    parameter.

    The constriction kernel accepts the inertia parameter only to maintain
    the same interface as the inertia formulation.
    """

    config = build_config("constriction")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0])
    prev_v = np.array([0.5])

    R1 = np.array([0.2])
    R2 = np.array([0.4])

    pbest = np.array([2.0])
    lbest = np.array([3.0])

    result1 = vel_fn(
        0.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    result2 = vel_fn(
        1000.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    assert_allclose(result1, result2)


def test_inertia_custom_acceleration_coefficients():
    """
    @brief Verify arbitrary acceleration coefficients are captured by the
    generated kernel.
    """

    C1 = 1.7
    C2 = 2.4

    config = build_config(
        "inertia",
        C1=C1,
        C2=C2
    )

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0])
    prev_v = np.array([0.2])

    R1 = np.array([0.5])
    R2 = np.array([0.25])

    pbest = np.array([2.0])
    lbest = np.array([4.0])

    result = vel_fn(
        0.6,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    expected = (
        0.6 * prev_v
        + C1 * R1 * (pbest - prev_x)
        + C2 * R2 * (lbest - prev_x)
    )

    assert_allclose(result, expected)
    

def test_constriction_custom_acceleration_coefficients():
    """
    @brief Verify arbitrary acceleration coefficients are correctly
    captured by the constriction kernel.

    Confirms that the generated kernel uses the values of C1 and C2
    supplied to the factory function.
    """

    C1 = 1.7
    C2 = 2.4

    config = build_config(
        "constriction",
        C1=C1,
        C2=C2
    )

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0])
    prev_v = np.array([0.2])

    R1 = np.array([0.5])
    R2 = np.array([0.25])

    pbest = np.array([2.0])
    lbest = np.array([4.0])

    result = vel_fn(
        0.0,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    phi = C1 + C2
    K = 2.0 / abs(
        2.0 - phi - np.sqrt(phi * phi - 4.0 * phi)
    )

    expected = K * (
        prev_v
        + C1 * R1 * (pbest - prev_x)
        + C2 * R2 * (lbest - prev_x)
    )

    assert_allclose(result, expected)


def test_inputs_are_not_modified():
    """
    @brief Verify velocity-update kernels do not modify input arrays.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0, 2.0])
    prev_v = np.array([0.1, 0.2])

    R1 = np.array([0.3, 0.4])
    R2 = np.array([0.5, 0.6])

    pbest = np.array([2.0, 3.0])
    lbest = np.array([4.0, 5.0])

    originals = [
        arr.copy()
        for arr in (prev_x, prev_v, R1, R2, pbest, lbest)
    ]

    vel_fn(
        0.5,
        prev_x,
        prev_v,
        R1,
        R2,
        pbest,
        lbest
    )

    for original, current in zip(
        originals,
        (prev_x, prev_v, R1, R2, pbest, lbest)
    ):
        assert np.array_equal(original, current)


def test_output_shape_and_dtype():
    """
    @brief Verify returned velocity arrays preserve shape and dtype.
    """

    config = build_config("inertia")

    vel_fn = make_update_velocity(config)

    prev_x = np.array([1.0, 2.0], dtype=np.float64)
    prev_v = np.array([0.1, 0.2], dtype=np.float64)

    result = vel_fn(
        0.5,
        prev_x,
        prev_v,
        np.ones(2),
        np.ones(2),
        np.array([2.0, 3.0]),
        np.array([3.0, 4.0])
    )

    assert result.shape == prev_x.shape
    assert result.dtype == np.float64


def test_invalid_equation_type():
    """
    @brief Verify unsupported dynamical equation types raise an exception.
    """

    config = build_config("not_a_valid_equation")

    with pytest.raises(NotImplementedError):
        make_update_velocity(config)
        
        
def test_velocity_update_matches_matlab_reference():
    """
    @brief Verify velocity update computation matches Matlab reference output.

    This regression test compares the Python implementation against
    reference data generated by the original Matlab implementation.
    """
    base_dir = Path(__file__).resolve().parent / "data/"
    N_x = 4
    config = build_config("inertia")
    
    # Load the reference data
    particle_init = list(np.loadtxt(base_dir / "Initialized_particles_matlab_1p_4x.txt"))
    particle_before = np.empty((2, N_x))
    for j in range(2):
        for x in range(N_x):
            particle_before[j, x] = particle_init.pop(0)
                
    particles = list(np.loadtxt(base_dir / "Iterated_particles_matlab_1p_4x.txt"))
    particle_after = np.empty((2, N_x))
    for j in range(2):
        for x in range(N_x):
            particle_after[j, x] = particles.pop(0)
            
    pbest = np.loadtxt(base_dir / "pbest_positions_matlab_1p_4x.txt")
    lbest = np.loadtxt(base_dir / "lbest_positions_matlab_1p_4x.txt")

    R1 = np.loadtxt(base_dir / "R1_vals_1p_4x.txt")
    R2 = np.loadtxt(base_dir / "R2_vals_1p_4x.txt")
    
    # calculate using python
    upd_vel_func = make_update_velocity(config)
    updated_velocity = upd_vel_func(0.9, 
                                    particle_before[0,:], 
                                    particle_before[1,:],
                                    R1,
                                    R2,
                                    pbest,
                                    lbest)
    
    # compare against matlab
    for x in range(N_x):
        assert updated_velocity[x] == particle_after[1, x]
    
        