# -*- coding: utf-8 -*-
"""
@file test_sobol.py

@brief Unit tests for Sobol quasirandom-value generation.

This module contains unit tests for the `make_sobol` factory function
defined in:

@code
PSO.options.value_generators.sobol
@endcode

The tests verify:

* Correct generation of Sobol values with requested dimensions
* Values are within the interval [0, 1)
* Reproducibility using integer seeds
* Independence of Sobol streams using different seeds
* Independent state between separately created generators
* Zero-length requests
* Generation across multiple dimensions
* Reproducibility using SeedSequence objects
* Correct selection of the run-specific seed
* Correct selection of the generator-specific seed
* Continuation of the Sobol sequence across multiple calls
* Support for arbitrary, non-power-of-two batch sizes
* Independence of the callable's M argument from the configured dimension

These tests are designed for use with pytest.

@author
Ben Carlson

@date
2026-09-09
"""
from dataclasses import dataclass, field
import numpy as np
import pytest

from options.value_generators.sobol import make_sobol

# SciPy intentionally warns when Sobol.random() is called with a
# non-power-of-two number of points. The PSO API supports arbitrary
# particle counts, so this behavior is expected and is not an error
# for these tests.
pytestmark = pytest.mark.filterwarnings(
    "ignore:The balance properties of Sobol' points require n to be a power of 2.:UserWarning"
    )

@dataclass
class MockPSOConfig:
    """
    @brief Lightweight configuration object for testing.

    This class provides only the configuration members required by
    `make_sobol`.

    @param N_x
    Number of dimensions in the Sobol sequence.

    @param seed_vals
    Two-dimensional collection of seeds indexed as
    `[generator_index][run_index]`.
    """
    N_x: int = 2
    seed_vals: list = field(
        default_factory=lambda: [
            np.array([0, 1], dtype=np.uint64),
            np.array([2, 3], dtype=np.uint64),
            np.array([4, 5], dtype=np.uint64),
        ]
    )


def test_sobol_generation_shape():
    """
    @brief Verify generated Sobol array has the requested shape.

    The returned callable should generate N rows and M columns according
    to the PSO value-generator interface. The number of columns is
    determined by `config.N_x`.
    """
    config = MockPSOConfig(
        N_x=3,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(10, 3)

    assert vals.shape == (10, 3)


def test_sobol_generation_range():
    """
    @brief Verify generated Sobol values lie in the interval [0, 1).

    Sobol points generated by SciPy should contain floating-point
    values greater than or equal to zero and strictly less than one.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(100, 5)

    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)


def test_seed_reproducibility():
    """
    @brief Verify identical seeds produce identical Sobol sequences.

    Two Sobol generators initialized with the same seed and dimension
    should produce identical scrambled Sobol points.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([42], dtype=np.uint64),
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 0, 0)

    vals1 = sobol1(20, 5)
    vals2 = sobol2(20, 5)

    np.testing.assert_array_equal(vals1, vals2)


def test_seed_independence():
    """
    @brief Verify different seeds produce different Sobol sequences.

    Different scrambling seeds should produce different Sobol
    sequences while retaining the same dimensionality.
    """
    config1 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([1], dtype=np.uint64),
            np.array([2], dtype=np.uint64),
            np.array([3], dtype=np.uint64),
        ],
    )

    config2 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([4], dtype=np.uint64),
            np.array([5], dtype=np.uint64),
            np.array([6], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config1, 0, 0)
    sobol2 = make_sobol(config2, 0, 0)

    vals1 = sobol1(20, 5)
    vals2 = sobol2(20, 5)

    assert not np.array_equal(vals1, vals2)


def test_sobol_streams_are_independent():
    """
    @brief Verify separate Sobol generators maintain independent state.

    Creating multiple generators with the same configuration should
    create separate Sobol engines. Advancing one generator must not
    affect the sequence produced by another generator.
    """
    config = MockPSOConfig(
        N_x=3,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 0, 0)

    first_vals = sobol1(10, 3)

    # Advance only sobol1.
    sobol1(10, 3)

    second_vals = sobol2(10, 3)

    # sobol2 should still produce the first sequence.
    np.testing.assert_array_equal(first_vals, second_vals)


def test_zero_length_request():
    """
    @brief Verify requesting zero Sobol points returns an empty array.

    A zero-length request should preserve the configured Sobol
    dimensionality while returning no points.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(0, 5)

    assert vals.shape == (0, 5)
    assert vals.size == 0


def test_sobol_generation_multiple_dimensions():
    """
    @brief Verify Sobol values are generated across multiple dimensions.

    This test verifies that the Sobol engine is initialized with the
    configured number of dimensions and produces the expected number
    of values.
    """
    config = MockPSOConfig(
        N_x=7,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(4, 7)

    assert vals.shape == (4, 7)
    assert vals.size == 28
    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)


def test_seed_sequence_reproducibility():
    """
    @brief Verify SeedSequence objects provide reproducible Sobol streams.

    Two equivalent NumPy SeedSequence objects should result in
    identical NumPy Generators and therefore identical scrambled
    Sobol sequences.
    """
    seed1 = np.random.SeedSequence(12345)
    seed2 = np.random.SeedSequence(12345)

    config1 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([seed1], dtype=object),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    config2 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([seed2], dtype=object),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config1, 0, 0)
    sobol2 = make_sobol(config2, 0, 0)

    np.testing.assert_array_equal(
        sobol1(20, 5),
        sobol2(20, 5),
    )


def test_run_index_selects_correct_seed():
    """
    @brief Verify run_int selects the corresponding seed.

    Different run indices should use their corresponding entries in
    `config.seed_vals`, resulting in different scrambled Sobol streams.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123, 456], dtype=np.uint64),
            np.array([789, 101112], dtype=np.uint64),
            np.array([131415, 161718], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 1, 0)

    vals1 = sobol1(20, 5)
    vals2 = sobol2(20, 5)

    assert not np.array_equal(vals1, vals2)


def test_generator_index_selects_correct_seed_array():
    """
    @brief Verify generator_index selects the corresponding seed array.
    
    Different generator indices should use different rows of
    `config.seed_vals`, resulting in different scrambled Sobol streams
    when the selected seeds differ.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )
    
    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 0, 1)
    
    vals1 = sobol1(20, 5)
    vals2 = sobol2(20, 5)
    
    assert not np.array_equal(vals1, vals2)


def test_repeated_calls_continue_sobol_sequence():
    """
    @brief Verify consecutive calls continue the same Sobol sequence.

    Calling the returned callable multiple times should advance the
    underlying Sobol engine rather than restarting the sequence.

    The combined output from two consecutive calls should therefore
    match the output from a single call requesting the same total
    number of points.
    """
    config = MockPSOConfig(
        N_x=3,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 0, 0)
    
    first = sobol1(10, 3)
    second = sobol1(10, 3)

    expected = sobol2(20, 3)

    np.testing.assert_array_equal(
        first,
        expected[:10],
    )
    np.testing.assert_array_equal(
        second,
        expected[10:],
    )


def test_arbitrary_batch_size():
    """
    @brief Verify Sobol generation supports non-power-of-two batch sizes.

    The implementation intentionally uses SciPy's `random()` method
    instead of `random_base2()`, allowing the PSO API to request an
    arbitrary number of particles.

    This test uses a batch size that is not a power of two.
    """
    config = MockPSOConfig(
        N_x=4,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(7, 4)

    assert vals.shape == (7, 4)
    assert vals.size == 28
    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)


def test_m_dimension_matches_configured_dimension():
    """
    @brief Verify the configured N_x dimension controls the Sobol engine.

    The M argument is part of the common value-generator interface, but
    the Sobol implementation obtains its actual dimensionality from
    `config.N_x`.

    This test verifies that the generated points use the configured
    dimensionality even when M differs from N_x.
    """
    config = MockPSOConfig(
        N_x=6,
        seed_vals=[
            np.array([123], dtype=np.uint64),
            np.array([456], dtype=np.uint64),
            np.array([789], dtype=np.uint64),
        ],
    )

    sobol = make_sobol(config, 0, 0)

    vals = sobol(8, 2)

    assert vals.shape == (8, 6)


def test_first_points_are_reproducible_across_new_generators():
    """
    @brief Verify newly created generators begin at the same sequence point.

    Two separately created Sobol generators using the same seed should
    begin at the same scrambled Sobol sequence position.
    """
    config = MockPSOConfig(
        N_x=4,
        seed_vals=[
            np.array([9876], dtype=np.uint64),
            np.array([12345], dtype=np.uint64),
            np.array([54321], dtype=np.uint64),
        ],
    )

    sobol1 = make_sobol(config, 0, 0)
    sobol2 = make_sobol(config, 0, 0)

    first1 = sobol1(1, 4)
    first2 = sobol2(1, 4)

    np.testing.assert_array_equal(first1, first2)
    