# -*- coding: utf-8 -*-
"""
@file test_halton.py

@brief Unit tests for Halton quasirandom-value generation.

This module contains unit tests for the `make_halton` factory function
defined in:

@code
PSO.options.value_generators.halton
@endcode

The tests verify:

* Correct generation of Halton values with requested dimensions
* Values are within the interval [0, 1)
* Reproducibility using integer seeds
* Independence of Halton streams using different seeds
* Independent state between separately created generators
* Zero-length requests
* Generation across multiple dimensions
* Reproducibility using SeedSequence objects
* Correct selection of the run-specific seed
* Correct selection of the generator-specific seed
* Continuation of the Halton sequence across multiple calls
* Support for arbitrary batch sizes
* Use of the configured search-space dimensionality

These tests are designed for use with pytest.

@author
Ben Carlson

@date
2026-09-09
"""
from dataclasses import dataclass, field
import numpy as np

from options.value_generators.halton import make_halton

# ============================================================================
# Test configuration
# ============================================================================

N_RUNS = 2
N_GENERATORS = 3

@dataclass
class MockPSOConfig:
    """
    @brief Lightweight configuration object for testing.
    
    This class provides only the configuration members required by
    `make_halton`.
    
    @param N_x
    Number of dimensions in the Halton sequence.
    
    @param seed_vals
    Three-element sequence containing the seeds associated with the
    position, velocity, and update generators. Each generator contains
    one seed for each PSO run.
    """
    N_x: int = 2
    seed_vals: list = field(
        default_factory=lambda: [
            np.array([123, 456], dtype=np.uint64),
            np.array([789, 101112], dtype=np.uint64),
            np.array([131415, 161718], dtype=np.uint64),
        ]
    )

# ============================================================================
# Basic generation
# ============================================================================

def test_halton_generation_shape():
    """
    @brief Verify generated Halton array has the requested shape.
    
    The returned callable should generate N rows and M columns, as
    specified by the PSO value-generator interface.
    """
    config = MockPSOConfig(N_x=3)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(10, 3)
    
    assert vals.shape == (10, 3)


def test_halton_generation_range():
    """
    @brief Verify generated Halton values lie in the interval [0, 1).
    
    Halton points generated by SciPy should contain floating-point
    values greater than or equal to zero and strictly less than one.
    """
    config = MockPSOConfig(N_x=5)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(100, 5)
    
    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)
    
    
def test_halton_generation_multiple_dimensions():
    """
    @brief Verify Halton values are generated across multiple dimensions.
    
    This test verifies that the Halton engine is initialized with the
    configured number of dimensions and produces the expected number
    of values.
    """
    config = MockPSOConfig(N_x=7)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(4, 7)
    
    assert vals.shape == (4, 7)
    assert vals.size == 28
    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)

# ============================================================================
# Seed behavior
# ============================================================================

def test_seed_reproducibility():
    """
    @brief Verify identical seeds produce identical Halton sequences.
    
    Two Halton generators initialized with the same run-specific seed,
    generator index, and dimension should produce identical scrambled
    Halton points.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([42, 43], dtype=np.uint64),
            np.array([100, 101], dtype=np.uint64),
            np.array([200, 201], dtype=np.uint64),
        ],
    )
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 0, 0)
    
    vals1 = halton1(20, 5)
    vals2 = halton2(20, 5)
    
    np.testing.assert_array_equal(vals1, vals2)


def test_seed_independence():
    """
    @brief Verify different seeds produce different Halton sequences.
    
    Different scrambling seeds should produce different Halton
    sequences while retaining the same dimensionality.
    """
    config1 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([1, 3], dtype=np.uint64),
            np.array([10, 30], dtype=np.uint64),
            np.array([100, 300], dtype=np.uint64),
        ],
    )
    config2 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([2, 4], dtype=np.uint64),
            np.array([20, 40], dtype=np.uint64),
            np.array([200, 400], dtype=np.uint64),
        ],
    )
    
    halton1 = make_halton(config1, 0, 0)
    halton2 = make_halton(config2, 0, 0)
    
    vals1 = halton1(20, 5)
    vals2 = halton2(20, 5)
    
    assert not np.array_equal(vals1, vals2)


def test_seed_sequence_reproducibility():
    """
    @brief Verify SeedSequence objects provide reproducible Halton streams.
    
    Two equivalent NumPy SeedSequence objects should result in identical
    NumPy Generators and therefore identical scrambled Halton sequences.
    """
    seed1 = np.random.SeedSequence(12345)
    seed2 = np.random.SeedSequence(12345)
    
    config1 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([seed1, np.random.SeedSequence(1)], dtype=object),
            np.array(
                [np.random.SeedSequence(2), np.random.SeedSequence(3)],
                dtype=object,
            ),
            np.array(
                [np.random.SeedSequence(4), np.random.SeedSequence(5)],
                dtype=object,
            ),
        ],
    )
    
    config2 = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([seed2, np.random.SeedSequence(1)], dtype=object),
            np.array(
                [np.random.SeedSequence(2), np.random.SeedSequence(3)],
                dtype=object,
            ),
            np.array(
                [np.random.SeedSequence(4), np.random.SeedSequence(5)],
                dtype=object,
            ),
        ],
    )
    
    halton1 = make_halton(config1, 0, 0)
    halton2 = make_halton(config2, 0, 0)
    
    np.testing.assert_array_equal(
        halton1(20, 5),
        halton2(20, 5),
    )


def test_run_index_selects_correct_seed():
    """
    @brief Verify run_index selects the corresponding seed.
    
    Different run indices should use their corresponding seeds from
    the selected generator's seed array, resulting in different
    scrambled Halton streams.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123, 456], dtype=np.uint64),
            np.array([789, 101112], dtype=np.uint64),
            np.array([131415, 161718], dtype=np.uint64),
        ],
    )
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 1, 0)
    
    vals1 = halton1(20, 5)
    vals2 = halton2(20, 5)
    
    assert not np.array_equal(vals1, vals2)


def test_generator_index_selects_correct_seed():
    """
    @brief Verify generator_index selects the corresponding seed array.
    
    Different generator indices should select seeds from the appropriate
    generator-specific row of `config.seed_vals`. Different generator
    seeds should produce different scrambled Halton streams.
    """
    config = MockPSOConfig(
        N_x=5,
        seed_vals=[
            np.array([123, 456], dtype=np.uint64),
            np.array([789, 101112], dtype=np.uint64),
            np.array([131415, 161718], dtype=np.uint64),
        ],
    )
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 0, 1)
    
    vals1 = halton1(20, 5)
    vals2 = halton2(20, 5)
    
    assert not np.array_equal(vals1, vals2)

# ============================================================================
# Generator state
# ============================================================================

def test_halton_streams_are_independent():
    """
    @brief Verify separate Halton generators maintain independent state.
    
    Creating multiple generators with the same configuration should
    create separate Halton engines. Advancing one generator must not
    affect the sequence produced by another generator.
    """
    config = MockPSOConfig(N_x=3)
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 0, 0)
    
    first_vals = halton1(10, 3)
    
    # Advance only halton1.
    halton1(10, 3)
    
    second_vals = halton2(10, 3)
    
    # halton2 should still produce the first sequence.
    np.testing.assert_array_equal(first_vals, second_vals)


def test_repeated_calls_continue_halton_sequence():
    """
    @brief Verify consecutive calls continue the same Halton sequence.
    
    Calling the returned callable multiple times should advance the
    underlying Halton engine rather than restarting the sequence.
    
    The combined output from two consecutive calls should therefore
    match the output from a single call requesting the same total
    number of points.
    """
    config = MockPSOConfig(N_x=3)
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 0, 0)
    
    first = halton1(10, 3)
    second = halton1(10, 3)
    
    expected = halton2(20, 3)
    
    np.testing.assert_array_equal(
        first,
        expected[:10],
    )
    np.testing.assert_array_equal(
        second,
        expected[10:],
    )


def test_first_points_are_reproducible_across_new_generators():
    """
    @brief Verify newly created generators begin at the same sequence point.
    
    Two separately created Halton generators using the same run-specific
    seed and generator index should begin at the same scrambled Halton
    sequence position.
    """
    config = MockPSOConfig(
        N_x=4,
        seed_vals=[
            np.array([9876, 9877], dtype=np.uint64),
            np.array([10000, 10001], dtype=np.uint64),
            np.array([20000, 20001], dtype=np.uint64),
        ],
    )
    
    halton1 = make_halton(config, 0, 0)
    halton2 = make_halton(config, 0, 0)
    
    first1 = halton1(1, 4)
    first2 = halton2(1, 4)
    
    np.testing.assert_array_equal(first1, first2)

# ============================================================================
# Edge cases and interface behavior
# ============================================================================

def test_zero_length_request():
    """
    @brief Verify requesting zero Halton points returns an empty array.
    
    A zero-length request should preserve the configured Halton
    dimensionality while returning no points.
    """
    config = MockPSOConfig(N_x=5)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(0, 5)
    
    assert vals.shape == (0, 5)
    assert vals.size == 0


def test_arbitrary_batch_size():
    """
    @brief Verify Halton generation supports arbitrary batch sizes.
    
    Unlike sequence generators that require power-of-two batch sizes,
    the Halton implementation uses SciPy's `random()` method and
    therefore supports an arbitrary number of requested points.
    
    This test uses a batch size that is not a power of two.
    """
    config = MockPSOConfig(N_x=4)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(7, 4)
    
    assert vals.shape == (7, 4)
    assert vals.size == 28
    assert np.all(vals >= 0.0)
    assert np.all(vals < 1.0)


def test_m_dimension_matches_configured_dimension():
    """
    @brief Verify the configured N_x dimension controls the Halton engine.
    
    The M argument is part of the common value-generator interface, but
    the Halton implementation obtains its actual dimensionality from
    `config.N_x`.
    
    This test verifies that the generated points use the configured
    dimensionality rather than the M argument.
    """
    config = MockPSOConfig(N_x=6)
    
    halton = make_halton(config, 0, 0)
    
    vals = halton(8, 2)
    
    assert vals.shape == (8, 6)
